server:
  port: 9090

# Kafka
kafka:
  bootstrapAddress: localhost:9092
message:
  kafka:
    topic: message-topic00

spring.kafka.bootstrap-servers:
  - localhost:9092

spring.kafka.consumer.properties.spring.json.trusted.packages: "*"
spring.kafka.consumer.auto-offset-reset: earliest
spring.kafka.consumer.group-id: xcasemanager-messenger-consumer
spring.kafka.consumer.value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.batch-size: 16384
spring.kafka.producer.buffer-memory: 33554432
spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
